services:
  # * Nodes
  camera_1:
    container_name: camera1
    image: ghcr.io/ad-sdl/camera_module:latest
    build:
      context: ../../camera_module
      dockerfile: Dockerfile
    profiles:
      - nodes
      - '' # Empty string allows service to start when no --profile is specified
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - NODE_CAMERA_ADDRESS=/dev/video0
      - NODE_URL=http://bats09.bio.anl.gov:2000
    env_file: ../.env
    network_mode: host
    privileged: true
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ../nodes/camera_1/settings.yaml:/home/madsci/settings.yaml
      - ../.madsci:/home/madsci/.madsci

  pf400_node:
    image: ghcr.io/ad-sdl/pf400_module:latest
    build:
      context: ../../pf400_module
      dockerfile: Dockerfile
    container_name: pf400_node
    profiles:
      - nodes
      - '' # Empty string allows service to start when no --profile is specified
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - NODE_PF400_IP=192.168.0.30
      - NODE_URL=http://bats09.bio.anl.gov:2002
    env_file: ../.env
    network_mode: host
    volumes:
      - ../nodes/pf400/settings.yaml:/home/madsci/settings.yaml
      - ../.madsci:/home/madsci/.madsci
    restart: unless-stopped

  ot2_gamma:
    container_name: ot2_gamma
    image: ghcr.io/ad-sdl/ot2_module
    build:
      context: ../../ot2_module
      dockerfile: Dockerfile
    profiles:
      - nodes
      - '' # Empty string allows service to start when no --profile is specified
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - NODE_OT2_IP=169.254.107.59
      - NODE_URL=http://bats09.bio.anl.gov:2003
    env_file: ../.env
    network_mode: host
    volumes:
      - ../nodes/gamma/settings.yaml:/home/madsci/settings.yaml
      - ../.madsci:/home/madsci/.madsci

        #ot2_beta:
        #  container_name: ot2_beta
        #  image: ghcr.io/ad-sdl/ot2_module
        #  build:
        #    context: ../../ot2_module
        #    dockerfile: Dockerfile
        #  profiles:
        #    - nodes
        #    - '' # Empty string allows service to start when no --profile is specified
        #  environment:
        #    - USER_ID=1000
        #    - GROUP_ID=1000
        #    - NODE_OT2_IP=146.137.240.101
        #    - NODE_URL=http://bats09.bio.anl.gov:2004
        #  env_file: ../.env
        #  network_mode: host
        #  volumes:
        #    - ../nodes/ot2_beta.node/settings.yaml:/home/madsci/settings.yaml
        #    - ../.madsci:/home/madsci/.madsci
